#!/usr/bin/env bash
# This bash script will configure an ubuntu machine to start an Ngnix server
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart